### ISSUE TITLE
Data with cuticle and muscles do not correspond, cuticle is rotating more than muscles ... therefore only timestep 0 can be used as a bindpose

### ISSUE THREAD

**Issue by gitmado** [openworm/skeletonExtraction#65]

**Comment by tarelli** [comment]
This should be resolved by the new data from @skhayrulin

**Comment by skhayrulin** [comment]
Data is preparing I hope tomorrow result will be

**Comment by tarelli** [comment]
![yoda-master](https://cloud.githubusercontent.com/assets/81127/5999999/43d7317a-aad0-11e4-8343-7f6ecb9895c2.gif)
