### ISSUE TITLE
Is the COLLADA available in this repo?

### ISSUE THREAD

**Issue by slarson** [openworm/skeletonExtraction#87]
Some folks are wanting to play around with it.  cc: @darryldmps

If so, can we add info about it to the readme?

Thanks!

**Comment by gitmado** [comment]
We are having all the collada models in dropbox folder only. In the repo,
there are only source codes used for generation of the collada files.

**Comment by slarson** [comment]
OK Gotcha.  For @darryldmps -- here's the folder in question:
https://www.dropbox.com/sh/wq9rrun27u7pjpi/AACq-D1NHV_KI22gLsCTCxtMa/animatedColladas?dl=0
ᐧ

**Comment by darryldmps** [comment]
Great, Thank you!

Darryl
