### ISSUE TITLE
Load multiple models for all muscles and cuticle  from different collada files

### ISSUE THREAD

**Issue by gidili** [openworm/skeletonExtraction#88]
- [x] load all 96 static muscles from different collada files
- [x] load all 96 muscles and cuticle from different collada files and animate

**Comment by gidili** [comment]
@mihairaulea after today's successful tests it's safe to say we can load all the muscles from indipendent collada files!

![screenshot 2015-03-16 19 22 42](https://cloud.githubusercontent.com/assets/68134/6674724/a1b75b80-cc13-11e4-8893-1ea69440be74.png)

Next step is show how we can load them from different files and animate them!

**Comment by slarson** [comment]
Hot!  Does this move on your screen?????  Movie plzz??

**Comment by gidili** [comment]
@slarson not just yet, we are still loading each muscle as static colladas to test the rendering of all that stuff together. But coming soon!

**Comment by gidili** [comment]
We have shown that the animation from separate collada files for each muscle and cuticle works ok in chrome (not in firefox but likely to be a a loading issue - loading will go away once we integrate into Geppetto and stream transformations).
