### ISSUE TITLE
Refactor code so that three.js is as much as possible untouched

### ISSUE THREAD

**Issue by gidili** [openworm/skeletonExtraction#89]
- [ ] Understand what changed in the modified version of three.js, see [here](https://github.com/openworm/skeletonExtraction/blob/master/ClientSide/README.md)
- [ ] Find a way to tell three.js to dynamically apply a transformation to a skeleton by providing a transformation matrix for each bone. The signature would be something like transformSkeleton(object,trasnformationMatrices), in its implementation we would read the object.skeleton.boneMatrices and multiply it by the transformation matrices. We would probably have to override object.skeleton.boneMatrices with the result of the multiplication at the end so that when three.js will read its content it will be ready to use.

**Comment by tarelli** [comment]
@mihairaulea @gidili see above if it makes sense
